changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Enhancement
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fixes
